timelog4/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from timelog4app.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('timelog4app.urls')),
]

timelog4app/urls.py
from django.conf.urls import url, include
from timelog4app.views import *
from django.urls import path

app_name = "timelog4app"

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^logout/$', logout_user, name='logout'),
    url(r'^login/', login_user, name='login'),
    url(r'^register/$', register_user, name='register'),
    url(r'^activities$', activity_list, name='activities'),
    url(r'^activity/form$', activity_form, name='activity_form'),
    path('activities/<int:activity_id>/', activity_details, name='activity'),
    url(r'^activities/(?P<activity_id>[0-9]+)/form$', activity_edit_form, name='activity_edit_form'),
    url(r'^time_allocations$', time_allocation_list, name='time_allocations'),  
]

timelog4app/models/activity.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse



class Activity(models.Model):

    app_user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    active = models.BooleanField(default=False)

    class Meta:
        verbose_name = ("Activity")
        verbose_name_plural = ("Activitys")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Activity_detail", kwargs={"pk": self.pk})

timelog4app/models/model_factory.py
import sqlite3


def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

timelog4app/models/time_allocation.py
from django.db import models
from .activity import Activity
from django.urls import reverse



class Time_Allocation(models.Model):

    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    start_time = models.CharField(max_length=50, null=True)
    stop_time = models.CharField(max_length=50, null=True)
    date = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("Time_Allocation")
        verbose_name_plural = ("Time_Allocations")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Time_Allocation_detail", kwargs={"pk": self.pk})

timelog4app/views/home.py
from django.shortcuts import render


def home(request):
    if request.method == 'GET':
        template = 'home.html'
        context = {}

        return render(request, template, context)

timelog4app/templates/activities/detail.html
{% extends 'shared/base.html' %} {% block content %}

<h1>{{ activity.name }}</h1>
{% if totals.days is 0 and totals.hours is 0 and totals.minutes is 0 %}
<h3>You haven't performed this activity yet!</h3>
{% elif totals.days is 0 and totals.hours is 0 %}
<h3>
  You've performed this activity for {{ totals.minutes }} minute(s)
</h3>
{% elif totals.days is 0 %}
<h3>
  You've performed this activity for {{ totals.hours }} hour(s) and
  {{ totals.minutes }} minute(s)
</h3>
{% else %}
<h3>
  You've performed this activity for {{ totals.days }} day(s),
  {{ totals.hours }} hour(s), and
  {{ totals.minutes }} minute(s)
</h3>
{% endif %}
<form action="{% url 'timelog4app:activity' activity.id %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="actual_method" value="DELETE" />
  <button>Delete</button>
</form>
<form
  action="{% url 'timelog4app:activity_edit_form' activity.id %}"
  method="GET"
>
  {% csrf_token %}
  <button>Edit</button>
</form>

{% endblock %}

timelog4app/templates/activities/form.html
{% extends 'shared/base.html' %} {% block content %}
<h1>Activity</h1>

{% if activity.id is not None %}
<form action="{% url 'timelog4app:activity' activity.id %}" method="post">
  {% else %}
  <form action="{% url 'timelog4app:activities' %}" method="post">
    {% endif %} {% csrf_token %}
    <fieldset>
      <label for="title">Activity: </label>
      <input id="title" type="text" name="title" value="{{ activity.name }}" />
    </fieldset>

    {% if activity.id is not None %}
    <input type="hidden" name="actual_method" value="PUT" />
    <input type="submit" value="Update" />
    {% else %}
    <input type="submit" value="Create" />
    {% endif %}
  </form>
</form>
{% endblock %}

timelog4app/templates/activities/list.html
{% extends 'shared/base.html' %}
{% block content %} 
{% load staticfiles %} 
{% block css %}
<link rel="stylesheet" href="{% static 'styles/activities.css' %}" />
{% endblock %}

<h1>Activities</h1>

<a href="{% url 'timelog4app:activity_form' %}">Add Activity</a>
<div class="activities">
  {% for activity in all_activities %}
  <div class="activity">
    <br />
    <a
      class="activity__name"
      href="{% url 'timelog4app:activity' activity.id %}"
    >
      {{ activity.name }}
    </a>
    <form class="start_button_container" action="{% url 'timelog4app:time_allocations'   %}" method="post">
      {% csrf_token %}
      <button class="start_button" >Start</button>
      <input name="activity_id" type="hidden" value="{{ activity.id }}" />
    </form>

    <br />
  </div>

  {% endfor %}
</div>
{% endblock %}

timelog4app/templates/home.html
{% extends 'shared/base.html' %} 
{% block content %} 
{% load staticfiles %} 
{%block css %}
<link rel="stylesheet" href="{% static 'styles/home.css' %}" />
{% endblock %}
<div class="home">
  <h1>Welcome to Time Log!</h1>
  <div>
    <form action="{% url 'timelog4app:login' %}">
      {% csrf_token %}
      <h3>
        Old Friends:
        <button type="submit">Login</button>
      </h3>
    </form>
  </div>
  <div>
    <form action="{% url 'timelog4app:register' %}">
      {% csrf_token %}
      <h3>
        New Friends:
        <button type="submit">Register</button>
      </h3>
    </form>
  </div>
</div>
{% endblock %}

timelog4app/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Time Log</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %} {% endblock %}
  </head>

  <body>
    <div class="white">
      <nav id="site-nav">
        <ul class="navList">
          <li class="navList__route">
            <a href="{% url 'timelog4app:activities' %}">Activities</a>
          </li>
          <li class="navList__route">
            <a href="{% url 'timelog4app:time_allocations' %}">Log</a>
          </li>
          <div class="logout">

            <li class="navList__route">
              <a href="{% url 'timelog4app:logout' %}">Logout</a>
            </li>
          </div>
        </ul>
      </nav>
    </div>

    <main content="main-content">
      {% block content %} {% endblock %}
    </main>

    {% block scripts %} {% endblock scripts %}
  </body>
</html>

timelog4app/templates/time_allocations/list.html
{% extends 'shared/base.html' %} {% block content %} 
{% load staticfiles %} 
{%block css %}
<link rel="stylesheet" href="{% static 'styles/allocations.css' %}" />
{% endblock %}

<table style="width:100%">
  <tr>
    <th>Activity</th>
    <th>Start Time</th>
    <th>Stop Time</th>
    <th>Action</th>
    <th>
      <form action="{% url 'timelog4app:time_allocations' %}" method="GET">
        See Log For
        <input name="desired_date" type="text" value="MM/DD/YY" />
        <input type="submit" value="Apply" />
      </form>
    </th>
  </tr>
  {% for each in all_time_allocations %}

  <tr>
    <td>{{ each.name }}</td>
    <td>{{ each.start_time }}</td>
    {% if each.stop_time is not None %}
    <td>{{ each.stop_time }}</td>
    {% else %}
    <td>--</td>
    {% endif %}

    <td>
      {% if each.stop_time is not None %}
      <form action="{% url 'timelog4app:time_allocations' %}" method="post">
        {% csrf_token %}

        <button>Delete</button>
        <input name="id_to_delete" type="hidden" value="{{ each.id }}" />
        <input name="actual_method" type="hidden" value="DELETE" />
      </form>
      {% else %}
      <form action="{% url 'timelog4app:time_allocations'   %}" method="post">
        {% csrf_token %}
        <button>Stop</button>
        <input name="activity_id_edited" type="hidden" value="{{ each.id }}" />
        <input name="actual_method" type="hidden" value="PUT" />
      </form>
      {% endif %}
    </td>
  </tr>
  {% endfor %}
  <tfoot>
    <tr></tr>
  </tfoot>
</table>
{% endblock %}